### ISSUE TITLE
This does not conform to RFC 7208

### ISSUE THREAD

**Issue by niftylettuce** [pboyd04/spf-validator#5]
<strike>See <https://tools.ietf.org/html/rfc4408></strike>

See <https://tools.ietf.org/html/rfc7208>

**Comment by pboyd04** [comment]
The 2.0 branch is aiming for full RFC compliance. It fails about 36 test cases right now, but most are things like returning fail when it should return permerror.

**Comment by jm42** [comment]
Nice to hear.

Currently there are no pure node implementations that do full compliance. I am currently using [node-spf-check](https://github.com/mediamonks/node-spf-check) but would be happy to switch over once domain specification is implemented (aka macros).

Also, RFC4408 has been deprecated in favour of [RFC7208](https://tools.ietf.org/html/rfc7208). Might be something to consider.

**Comment by pboyd04** [comment]
Yeah, I'm actually running the full openspf test suite for both RFC against the 2.0 branch right now. It's mostly macro stuff that is failing at the moment.

**Comment by niftylettuce** [comment]
@pboyd04 	can you toss me an email at niftylettuce@gmail.com?  wanted to ask you a question over email in particular (not necessarily related to this project)

**Comment by niftylettuce** [comment]
Check out https://github.com/niftylettuce/python-spfcheck2 - something temporary I made for now, very well documented too and it's RFC 4408 and RFC 7208 compliant 😄 

cc @pboyd04 @jm42
